extract: handle better the help message, don't always exit with 1

diff --git a/extract b/extract
--- a/extract
+++ b/extract
@@ -4,13 +4,14 @@ help() {
     echo
     echo "Extracts the file specified based on the extension"
     echo "Stolen from http://dev.gentoo.org/~steev/files/zshrc"
-    echo "Usage: extract <filename>"
+    echo "Usage: `basename "$0"` <filename>"
     echo
-    exit 1
 }
 
-[ -z "$1" ] && help
-[ "$1" == "--help" ] && help
+case $1 in
+    '-h'|'--help') help ;;
+    '') help && exit 1 ;;
+esac
 
 if [ -f "$1" ]; then
     case "${1}" in
@@ -26,8 +27,12 @@ if [ -f "$1" ]; then
         *.gem) gem unpack "$1" ;;
         *.rpm) unrpm "$1" ;;
         *.7z) 7z e "$1" ;;
-        *) echo "Unable to extract '$1': Unknown extension"
+        *)
+            echo "Unable to extract '$1': Unknown extension"
+            exit 1
+            ;;
     esac
 else
     echo "Unable to extract '$1': File not found"
+    exit 1
 fi
